"""add region to permit_projects

Revision ID: 4f9d56aedd52
Revises: d8269d3ed50d
Create Date: 2026-04-27 12:25:21.009710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9d56aedd52'
down_revision: Union[str, Sequence[str], None] = 'd8269d3ed50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permit_projects', sa.Column('region', sa.String(), server_default='vl', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permit_projects', 'region')
    # ### end Alembic commands ###
