"""initial

Revision ID: e9761d793952
Revises: 
Create Date: 2026-04-26 12:57:25.354233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9761d793952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permit_projects',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('omv_reference', sa.String(), nullable=False),
    sa.Column('detail_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('trees_to_fell', sa.Integer(), nullable=True),
    sa.Column('mer_status', sa.String(), nullable=True),
    sa.Column('iioa_class', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision_outcome', sa.String(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('dossier_pdfs', sa.JSON(), nullable=False),
    sa.Column('overlays', sa.JSON(), nullable=True),
    sa.Column('raw_html_path', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('decision_regime', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('scrape_state',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cursor', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('public_inquiries',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('project_external_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('objection_deadline', sa.Date(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('objection_count_known', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_external_id'], ['permit_projects.external_id'], ),
    sa.PrimaryKeyConstraint('external_id')
    )
    op.create_table('risk_assessments',
    sa.Column('project_external_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('expected_delay_days', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('top_risks', sa.JSON(), nullable=False),
    sa.Column('calibration_regime', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inputs_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_external_id'], ['permit_projects.external_id'], ),
    sa.PrimaryKeyConstraint('project_external_id', 'engine_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_table('public_inquiries')
    op.drop_table('scrape_state')
    op.drop_table('permit_projects')
    # ### end Alembic commands ###
